export default {
  exit: require('../assets/images/exit.png'),
  eula: require('../assets/images/eula.png'),
  rate: require('../assets/images/rate.png'),
  recomend: require('../assets/images/recomend.png'),
  security: require('../assets/images/security.png'),
  support: require('../assets/images/support.png'),
  cardiology: require('../assets/images/cardiology.png'),
  dermatology: require('../assets/images/dermatology.png'),
  ent: require('../assets/images/ent.png'),
  eye: require('../assets/images/eye.png'),
  infectious: require('../assets/images/infectious.png'),
  internal: require('../assets/images/internal.png'),
  logo: require('../assets/images/logo.png'),
  obs: require('../assets/images/obs.png'),
  pediatric: require('../assets/images/pediatric.png'),
  splashbg: require('../assets/images/splashbg.png'),
  urology: require('../assets/images/urology.png'),
  back: require('../assets/images/back.png'),
  select: require('../assets/images/select.png'),
  searchsettings: require('../assets/images/searchsettings.png'),
  womandr: require('../assets/images/womandr.png'),
  mendr: require('../assets/images/mendr.png'),
  plus: require('../assets/images/plus.png'),
  tabs1: require('../assets/images/tabs1.png'),
  tabs2: require('../assets/images/tabs2.png'),
  tabs3: require('../assets/images/tabs3.png'),
  tabs4: require('../assets/images/tabs4.png'),
  blue: require('../assets/images/blue.png'),
  orange: require('../assets/images/orange.png'),
  navyblue: require('../assets/images/navyblue.png'),
  purple: require('../assets/images/purple.png'),
  search: require('../assets/images/search.png'),
  line: require('../assets/images/line.png'),
  bigdr: require('../assets/images/bigdr.png'),
  heart: require('../assets/images/heart.png'),
  king: require('../assets/images/king.png'),
  rating: require('../assets/images/rating.png'),
  star: require('../assets/images/star.png'),
  image: require('../assets/images/image.png'),
  good: require('../assets/images/good.png'),
  credit: require('../assets/images/credit.png'),
  google: require('../assets/images/google.png'),
  apple: require('../assets/images/apple.png'),
  paypal: require('../assets/images/paypal.png'),

  //********************FLAG*****************************/

  de: require('../assets/images/Flag/de.png'),
  es: require('../assets/images/Flag/es.png'),
  fr: require('../assets/images/Flag/fr.png'),
  hi: require('../assets/images/Flag/hi.png'),
  id: require('../assets/images/Flag/id.png'),
  it: require('../assets/images/Flag/it.png'),
  pt: require('../assets/images/Flag/pt.png'),
  tr: require('../assets/images/Flag/tr.png'),
  en: require('../assets/images/Flag/en.png'),
};
